### ISSUE TITLE
[feat] Gateway Upgradeable

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/succinct-starknet#1]
Implement OZ `upgradeable` for the succinct gateway:
- https://github.com/keep-starknet-strange/succinct-starknet/blob/4b76805324d9e61464e7fec6ee8bbb22a773a95d/src/gateway.cairo#L2

## Ref
- https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/upgrades/upgradeable.cairo

**Comment by Akashneelesh** [comment]
Hello @drspacemn , I have implemented this as well and will be raising PR.
