### ISSUE TITLE
[dev] Use Alexandria's sol_abi Traits

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/succinct-starknet#11]
`Alexandria` now has the `sol_abi` library, which provides a similar DevEx to Solidity for bytes encoding/decoding.
It would be helpful to change our `append_X` and `read_X` calls throughout the code to `encode_packed` and `decode` calls. This would make future development more accessible and maybe provide some insight into the new `sol_abi` traits.

### References

- [Alexandria sol_abi traits](https://github.com/keep-starknet-strange/alexandria/tree/main/src/encoding#solidity-abi)
- [Example append to replace with encode_packed](https://github.com/keep-starknet-strange/succinct-starknet/blob/4c780fba08013f7166567985b676a344a22eec9f/src/gateway.cairo#L352)
- [Example read to replace with decode](https://github.com/keep-starknet-strange/succinct-starknet/blob/4c780fba08013f7166567985b676a344a22eec9f/src/gateway.cairo#L305)

**Comment by 0xthomass** [comment]
Hey, I'll do this one
