### ISSUE TITLE
[feat] Allowed Provers Funcs

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/succinct-starknet#2]
Add `get_` and `set_` functions for querying and updating the `allowed_provers` map.

Action should only be taken/allowed by the contract owner.
- ref -> https://github.com/succinctlabs/succinctx/blob/b272dbbd19af831a313f78b61d6571b26230e048/contracts/src/SuccinctGateway.sol#L280

Calls to `fulfill_call` and `fullfill_callback` should only be allowed by provers whitelisted in `allowed_provers` map:
- https://github.com/succinctlabs/succinctx/blob/b272dbbd19af831a313f78b61d6571b26230e048/contracts/src/SuccinctGateway.sol#L47

**Comment by Akashneelesh** [comment]
Heyy @drspacemn , may I take this one up.
