### ISSUE TITLE
[feat] Set Fee Vault

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/succinct-starknet#7]
Add the `set_` and `get_` functions for the `fee_vault_address` in the Gateway contract. Also, add the corresponding `SetFeeVault` event.

#### References
Code from solidity SuccinctGateway.sol https://github.com/succinctlabs/succinctx/blob/18611dc4ff59ac53f895cd45588d562f0c088758/contracts/src/SuccinctGateway.sol#L338

**Comment by Akashneelesh** [comment]
I have raised PR for the same.
